package py.org.pti.example.server.model;

// Generated 18/06/2014 08:18:20 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * States generated by hbm2java
 */
@Entity
@Table(name = "states", schema = "public")
public class State implements java.io.Serializable
{
    /**
     * 
     */
    private static final long serialVersionUID = 996592011706806228L;
    
    private Long id;
    private Country country;
    private String name;
    private Boolean active;
    private Set<City> cities = new HashSet<City>(0);

    public State()
    {
    }

    public State(Country country)
    {
        this.country = country;
    }

    private final static String SEQUENCE_GENERATOR = "STATE_SEQUENCE_GENERATOR";

    @Id
    @SequenceGenerator(name = SEQUENCE_GENERATOR, sequenceName = "states_id_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_GENERATOR)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "country_id", nullable = false)
    public Country getCountry()
    {
        return this.country;
    }

    public void setCountry(Country countries)
    {
        this.country = countries;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @Column(name = "active")
    public Boolean getActive()
    {
        return this.active;
    }

    public void setActive(Boolean active)
    {
        this.active = active;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "state")
    public Set<City> getCities()
    {
        return this.cities;
    }

    public void setCities(Set<City> citieses)
    {
        this.cities = citieses;
    }

}
