package py.org.icarusdb.example.server.model;

// Generated 18/06/2014 08:18:20 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Continents generated by hbm2java
 */
@Entity
@Table(name = "continents", schema = "public")
public class Continent implements java.io.Serializable
{
    /**
     * 
     */
    private static final long serialVersionUID = -2407161521178487490L;
    
    private Long id;
    private String name;
    private Boolean active;
    private Set<Country> countries = new HashSet<Country>(0);

    private final static String SEQUENCE_GENERATOR = "CONTINENTS_SEQUENCE_GENERATOR";

    @Id
    @SequenceGenerator(name = SEQUENCE_GENERATOR, sequenceName = "continents_id_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_GENERATOR)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @Column(name = "active")
    public Boolean getActive()
    {
        return this.active;
    }

    public void setActive(Boolean active)
    {
        this.active = active;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "continent")
    public Set<Country> getCountries()
    {
        return this.countries;
    }

    public void setCountries(Set<Country> countrieses)
    {
        this.countries = countrieses;
    }

}
