package py.org.icarusdb.example.server.model;

// Generated 18/06/2014 08:18:20 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name = "countries", schema = "public")
public class Country implements java.io.Serializable
{
    /**
     * 
     */
    private static final long serialVersionUID = 6132246144116117546L;
    
    private Long id;
    private Continent continent;
    private String name;
    private Boolean active;
    private Set<State> states = new HashSet<State>(0);

    public Country()
    {
    }

    public Country(Continent continent)
    {
        this.continent = continent;
    }

    private final static String SEQUENCE_GENERATOR = "COUNTRIES_SEQUENCE_GENERATOR";

    @Id
    @SequenceGenerator(name = SEQUENCE_GENERATOR, sequenceName = "countries_id_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_GENERATOR)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH, CascadeType.DETACH})
    @JoinColumn(name = "continent_id", nullable = false)
    public Continent getContinent()
    {
        return this.continent;
    }

    public void setContinent(Continent continent)
    {
        this.continent = continent;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @Column(name = "active")
    public Boolean getActive()
    {
        return this.active;
    }

    public void setActive(Boolean active)
    {
        this.active = active;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
    public Set<State> getStates()
    {
        return this.states;
    }

    public void setStates(Set<State> stateses)
    {
        this.states = stateses;
    }

}
